In [7]:
import json
import logging
import os
from pathlib import Path

import boto3
import ipynbname
import numpy as np
import pandas as pd
from dotenv import load_dotenv

In [ ]:
p = ipynbname.path().parent.parent

format = '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
filename_path = Path(p / 'logs' / 'transform_data.log')
logging.basicConfig(format=format, filename=filename_path, encoding='utf-8', level=logging.INFO)
logger = logging.getLogger(__name__)

load_dotenv(dotenv_path=p / '.env')

def extract_data():
    if not os.getenv('API_KEY'):
        logger.error("API_KEY is not set in the environment variables.")
        raise TypeError("Expected string for API_KEY, received None (API_KEY is not set in the environment variables).")

    try:
        s3_client = boto3.client(
            's3', 
            aws_access_key_id=os.getenv('AWS_ACCESS_KEY_ID'), 
            aws_secret_access_key=os.getenv('AWS_SECRET_ACCESS_KEY')
        )
        response = s3_client.get_object(
            Bucket=os.getenv('S3_BUCKET_NAME'), 
            Key=f"bronze/mercadolivre/celulares-e-telefones/2026-10-18 10:24:00.662699-03:00/bronze_data.json"
        )
        data = json.loads(response['Body'].read().decode('utf-8'))
        logger.info("bronze_data.json obtained from Amazon S3")
        return data
    except Exception as e:
        logger.error(f"Error occurred while extracting data from Amazon S3: {e}")
        raise

In [9]:
pd.set_option('display.max_colwidth', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

def create_dataframe() -> pd.DataFrame:
    data = extract_data()
    df = pd.json_normalize(data)
    return df

df = create_dataframe()

def normalize_df(df: pd.DataFrame) -> pd.DataFrame:
    df_data_items = df.explode('data.items', ignore_index=True)
    df_items = pd.json_normalize(df_data_items['data.items'])
    df = pd.concat(
        [df_data_items, df_items],
        axis=1
    )
    return df

df = normalize_df(df)
df.head()

,requestId,executionId,data.source,data.type,data.url,data.requestUrl,data.extractedAt,data.query,data.totalResults,data.primaryResults,data.page,data.resultsPerPage,data.offset,data.nextPage,data.nextPageUrl,data.items,url,imageUrl,sku,categoryId,domainId,name,condition,currency,currencyRaw,price,highlight,isBestSeller,isPowerSeller,powerSellerStatusTitle,ean,sellerId,sellerName,sellerCity,sellerState,sellerCountry,aggregateRating.rating,aggregateRating.reviewCount,aggregateRating
0,387feeae-070a-4537-8b94-4d3f0ad85e89,be922232-dd06-4bec-95b1-031ec26d9d25,mercadolivre.com.br,plp,https://lista.mercadolivre.com.br/iphone-15-pro-max,https://lista.mercadolivre.com.br/iphone-15-pro-max,2026-10-18T13:23:12.225Z,iphone 15 pro max,196,196,1,48,0,2.0,https://lista.mercadolivre.com.br/celulares-telefones/celulares-smartphones/iphone/iphone-15-pro-max/iphone-15-pro-max_Desde_49_NoIndex_True,"{'url': 'https://www.mercadolivre.com.br/apple-iphone-15-pro-max-256-gb-titanio-branco-bom-recondicionado/p/MLB2000117258', 'imageUrl': 'https://http2.mlstatic.com/D_Q_NP_2X_666226-MLA95937699435_102025-E.webp', 'sku': 'MLB5131015321', 'categoryId': 'MLB1055', 'domainId': 'MLB-CELLPHONES', 'name': 'Apple iPhone 15 Pro Max (256 GB) - Titânio Branco - Bom (Recondicionado)', 'condition': 'Recondicionado', 'currency': 'BRL', 'currencyRaw': 'R$', 'price': 4418, 'highlight': None, 'isBestSeller': False, 'isPowerSeller': False, 'powerSellerStatusTitle': None, 'aggregateRating': {'rating': 4.6, 'reviewCount': None}, 'ean': None, 'sellerId': None, 'sellerName': 'Mobi Phone', 'sellerCity': None, 'sellerState': None, 'sellerCountry': None}",https://www.mercadolivre.com.br/apple-iphone-15-pro-max-256-gb-titanio-branco-bom-recondicionado/p/MLB2000117258,https://http2.mlstatic.com/D_Q_NP_2X_666226-MLA95937699435_102025-E.webp,MLB5131015321,MLB1055,MLB-CELLPHONES,Apple iPhone 15 Pro Max (256 GB) - Titânio Branco - Bom (Recondicionado),Recondicionado,BRL,R$,4418,NaN,False,False,None,None,None,Mobi Phone,None,None,None,4.6,NaN,NaN
1,387feeae-070a-4537-8b94-4d3f0ad85e89,be922232-dd06-4bec-95b1-031ec26d9d25,mercadolivre.com.br,plp,https://lista.mercadolivre.com.br/iphone-15-pro-max,https://lista.mercadolivre.com.br/iphone-15-pro-max,2026-10-18T13:23:12.225Z,iphone 15 pro max,196,196,1,48,0,2.0,https://lista.mercadolivre.com.br/celulares-telefones/celulares-smartphones/iphone/iphone-15-pro-max/iphone-15-pro-max_Desde_49_NoIndex_True,"{'url': 'https://www.mercadolivre.com.br/apple-iphone-15-pro-max-256-gb-titanio-branco-novo-com-caixa-aberta/p/MLB2016209824', 'imageUrl': 'https://http2.mlstatic.com/D_Q_NP_2X_666226-MLA95937699435_102025-E.webp', 'sku': 'MLB5139760719', 'categoryId': 'MLB1055', 'domainId': 'MLB-CELLPHONES', 'name': 'Apple iPhone 15 Pro Max (256 GB) - Titânio Branco (Novo com caixa aberta)', 'condition': 'Caixa aberta', 'currency': 'BRL', 'currencyRaw': 'R$', 'price': 5113, 'highlight': 'ÚLTIMAS 3', 'isBestSeller': False, 'isPowerSeller': False, 'powerSellerStatusTitle': None, 'aggregateRating': {'rating': 4, 'reviewCount': None}, 'ean': None, 'sellerId': None, 'sellerName': None, 'sellerCity': None, 'sellerState': None, 'sellerCountry': None}",https://www.mercadolivre.com.br/apple-iphone-15-pro-max-256-gb-titanio-branco-novo-com-caixa-aberta/p/MLB2016209824,https://http2.mlstatic.com/D_Q_NP_2X_666226-MLA95937699435_102025-E.webp,MLB5139760719,MLB1055,MLB-CELLPHONES,Apple iPhone 15 Pro Max (256 GB) - Titânio Branco (Novo com caixa aberta),Caixa aberta,BRL,R$,5113,ÚLTIMAS 3,False,False,None,None,None,NaN,None,None,None,4.0,NaN,NaN
2,387feeae-070a-4537-8b94-4d3f0ad85e89,be922232-dd06-4bec-95b1-031ec26d9d25,mercadolivre.com.br,plp,https://lista.mercadolivre.com.br/iphone-15-pro-max,https://lista.mercadolivre.com.br/iphone-15-pro-max,2026-10-18T13:23:12.225Z,iphone 15 pro max,196,196,1,48,0,2.0,https://lista.mercadolivre.com.br/celulares-telefones/celulares-smartphones/iphone/iphone-15-pro-max/iphone-15-pro-max_Desde_49_NoIndex_True,"{'url': 'https://www.mercadolivre.com.br/apple-iphone-15-pro-max-256-gb-titanio-branco/p/MLB27172715', 'imageUrl': 'https://http2.mlstatic.com/D_Q_NP_2X_666226-MLA95937699435_102025-E.webp', 'sku': 'MLB7549855162', 'categoryId': 'MLB1055', 'domainId': 'MLB-CELLPHONES', 'name': 'Apple iPhone 15 Pro Max (256 GB) - Titânio Branco', 'condition': None, 'currency': 'BRL', 'currencyRaw': 'R$', 'price': 6599, 'highlight': 'ÚLTIMAS 4', 'isBestSeller': False, 'isPowerSeller': False, 'powerSellerStatusTitle': None, 'aggregateRating': {'rating': 4.7, 'reviewCount': None}, 'ean': None, 'sellerId': None, 'sellerName': None, 'sellerCity': None, 'sellerState': None, 'sellerCountry': None}",https://www.mercadolivre.com.br/apple-iphone-15-pro-max-256-gb-titanio-branco/p/MLB27172715,https://http2.mlstatic.com/D_Q_NP_2X_666226-MLA95937699435_102025-E.webp,MLB7549855162,MLB1055,MLB-CELLPHONES,Apple iPhone 15 Pro Max (256 GB) - Titânio Branco,NaN,BRL,R$,6599,ÚLTIMAS 4,False,False,None,None,None,NaN,None,None,None,4.7,NaN,NaN
3,387feeae-070a-4537-8b94-4d3f0ad85e89,be922232-dd06-4bec-95b1-031ec26d9d25,mercadolivre.com.br,plp,https://lista.mercadolivre.com.br/iphone-15-pro-max,https://lista.mercadolivre.com.br/iphone-15-pro-max,2026-10-18T13:23:12.225Z,iphone 15 pro max,196,196,1,48,0,2.0,https://lista.mercadolivre.com.br/celulares-telefones/celulares-smartphones/iphone/iphone-15-pro-max/iphone-15-pro-max_Desde_49_NoIndex_True,"{'url': 'https://www.mercadolivre.com.br/apple-iphone-15-pro-max-512-gb-titanio-azul/p/MLB27172716', 'imageUrl': 'https://http2.mlstatic.com/D_Q_NP_2X_688773-MLA95494114970_102025-E.webp', 'sku': 'MLB5183390473', 'categoryId': 'MLB1055', 'domainId': 'MLB-CELLPHONES', 'name': 'Apple iPhone 15 Pro Max (512 GB) - Titânio Azul', 'condition': None, 'currency': 'BRL', 'currencyRaw': 'R$', 'price': 7799, 'highlight': None, 'isBestSeller': False, 'isPowerSeller': False, 'powerSellerStatusTitle': None, 'aggregateRating': {'rating': 4.7, 'reviewCount': None}, 'ean': None, 'sellerId': None, 'sellerName': None, 'sellerCity': None, 'sellerState': None, 'sellerCountry': None}",https://www.mercadolivre.com.br/apple-iphone-15-pro-max-512-gb-titanio-azul/p/MLB27172716,https://http2.mlstatic.com/D_Q_NP_2X_688773-MLA95494114970_102025-E.webp,MLB5183390473,MLB1055,MLB-CELLPHONES,Apple iPhone 15 Pro Max (512 GB) - Titânio Azul,NaN,BRL,R$,7799,NaN,False,False,None,None,None,NaN,None,None,None,4.7,NaN,NaN
4,387feeae-070a-4537-8b94-4d3f0ad85e89,be922232-dd06-4bec-95b1-031ec26d9d25,mercadolivre.com.br,plp,https://lista.mercadolivre.com.br/iphone-15-pro-max,https://lista.mercadolivre.com.br/iphone-15-pro-max,2026-10-18T13:23:12.225Z,iphone 15 pro max,196,196,1,48,0,2.0,https://lista.mercadolivre.com.br/celulares-telefones/celulares-smartphones/iphone/iphone-15-pro-max/iphone-15-pro-max_Desde_49_NoIndex_True,"{'url': 'https://www.mercadolivre.com.br/apple-iphone-15-pro-max-256gb-titanio-natural-5g-original/up/MLBU3952749894', 'imageUrl': 'https://http2.mlstatic.com/D_Q_NP_2X_931212-MLB117528231503_092026-E.webp', 'sku': 'MLB6731711602', 'categoryId': 'MLB1055', 'domainId': 'MLB-CELLPHONES', 'name': 'Apple iPhone 15 Pro Max 256gb Titânio Natural 5g Original (Novo com caixa aberta)', 'condition': 'Caixa aberta', 'currency': 'BRL', 'currencyRaw': 'R$', 'price': 5484, 'highlight': None, 'isBestSeller': False, 'isPowerSeller': False, 'powerSellerStatusTitle': None, 'aggregateRating': {'rating': 4.5, 'reviewCount': None}, 'ean': None, 'sellerId': None, 'sellerName': None, 'sellerCity': None, 'sellerState': None, 'sellerCountry': None}",https://www.mercadolivre.com.br/apple-iphone-15-pro-max-256gb-titanio-natural-5g-original/up/MLBU3952749894,https://http2.mlstatic.com/D_Q_NP_2X_931212-MLB117528231503_092026-E.webp,MLB6731711602,MLB1055,MLB-CELLPHONES,Apple iPhone 15 Pro Max 256gb Titânio Natural 5g Original (Novo com caixa aberta),Caixa aberta,BRL,R$,5484,NaN,False,False,None,None,None,NaN,None,None,None,4.5,NaN,NaN

In [10]:
drop_columns = [
    'requestId', 'executionId', 'data.source', 'data.type', 'data.url', 
    'data.requestUrl', 'data.query', 'data.totalResults', 'data.primaryResults', 
    'data.page', 'data.resultsPerPage', 'data.offset', 'data.nextPage', 
    'data.nextPageUrl', 'data.items', 'aggregateRating'
]

def normalize_unnecessary(df: pd.DataFrame, drop_columns: list) -> pd.DataFrame:
    df_drop = df.drop(drop_columns, axis=1)
    return df_drop

df = normalize_unnecessary(df, drop_columns)
resume = pd.DataFrame({
    'dtype': df.dtypes,
    'total': len(df),
    'not_null': df.notna().sum(),
    'nulls': df.isna().sum(),
    'unique': df.nunique()
})
print(resume)

                               dtype  total  not_null  nulls  unique
data.extractedAt                 str    196       196      0       5
url                              str    196       196      0     191
imageUrl                         str    196       196      0     187
sku                              str    196       196      0     191
categoryId                       str    196       196      0       1
domainId                         str    196       196      0       1
name                             str    196       196      0     127
condition                        str    196       193      3       3
currency                         str    196       196      0       1
currencyRaw                      str    196       196      0       1
price                          int64    196       196      0     132
highlight                        str    196        12    184       5
isBestSeller                    bool    196       196      0       1
isPowerSeller                   bool    196       196      0       1
powerSellerStatusTitle        object    196         0    196       0
ean                           object    196         0    196       0
sellerId                      object    196         0    196       0
sellerName                       str    196         9    187       3
sellerCity                    object    196         0    196       0
sellerState                   object    196         0    196       0
sellerCountry                 object    196         0    196       0
aggregateRating.rating       float64    196         7    189       4
aggregateRating.reviewCount  float64    196         0    196       0

In [11]:
def normalize_null(df: pd.DataFrame) -> pd.DataFrame:
    for i in df.columns:
        if df[i].notna().sum() == 0:
            df.drop(i, axis=1, inplace=True)

    return df

def normalize_unique(df: pd.DataFrame) -> pd.DataFrame:
    for i in df.columns:
        if df[i].nunique() == 1:
            df.drop(i, axis=1, inplace=True)

    return df

df = normalize_null(df)
df = normalize_unique(df)

remained_columns = list(df.columns)

resume = pd.DataFrame({
    'total': len(df),
    'not_null': df.notna().sum(),
    'nulls': df.isna().sum(),
    'unique': df.nunique()
})
print(resume)
print("\n")
remained_columns

                        total  not_null  nulls  unique
data.extractedAt          196       196      0       5
url                       196       196      0     191
imageUrl                  196       196      0     187
sku                       196       196      0     191
name                      196       196      0     127
condition                 196       193      3       3
price                     196       196      0     132
highlight                 196        12    184       5
sellerName                196         9    187       3
aggregateRating.rating    196         7    189       4

['data.extractedAt',
 'url',
 'imageUrl',
 'sku',
 'name',
 'condition',
 'price',
 'highlight',
 'sellerName',
 'aggregateRating.rating']

In [12]:
def normalize_dataextractedat(df: pd.DataFrame) -> pd.DataFrame:
    if 'data.extractedAt' in remained_columns:
        df['data.extractedAt'] = pd.to_datetime(df['data.extractedAt'])
        df['data.extractedAt'] = df['data.extractedAt'].dt.tz_convert('America/Sao_Paulo')

    return df

df = normalize_dataextractedat(df)
print(df.dtypes)

data.extractedAt          datetime64[us, America/Sao_Paulo]
url                                                     str
imageUrl                                                str
sku                                                     str
name                                                    str
condition                                               str
price                                                 int64
highlight                                               str
sellerName                                              str
aggregateRating.rating                              float64
dtype: object

In [13]:
resume = pd.DataFrame({
    'dtype': df.dtypes,
    'total': len(df),
    'not_null': df.notna().sum(),
    'nulls': df.isna().sum(),
    'unique': df.nunique()
})
print(f"\nBefore:\n{resume}")

def treat_identification_columns(df: pd.DataFrame) -> pd.DataFrame:
    #nulls and empty strings
    df = df.replace(r'^\s*$', np.nan, regex=True)
    df = df.dropna(subset=['url', 'sku'], ignore_index=True)
    #unique
    df.drop_duplicates(subset=['url', 'sku'], inplace=True, ignore_index=True)

    other_columns = [col for col in df.columns if col not in ['url', 'sku']]
    df = df.reindex(columns=['url', 'sku'] + other_columns)
    
    return df

df = treat_identification_columns(df)
resume = pd.DataFrame({
    'dtype': df.dtypes,
    'total': len(df),
    'not_null': df.notna().sum(),
    'nulls': df.isna().sum(),
    'unique': df.nunique()
})
print(f"\nAfter:\n{resume}")

Before:
                                                    dtype  total  not_null  \
data.extractedAt        datetime64[us, America/Sao_Paulo]    196       196
url                                                   str    196       196
imageUrl                                              str    196       196
sku                                                   str    196       196
name                                                  str    196       196
condition                                             str    196       193
price                                               int64    196       196
highlight                                             str    196        12
sellerName                                            str    196         9
aggregateRating.rating                            float64    196         7

                        nulls  unique
data.extractedAt            0       5
url                         0     191
imageUrl                    0     187
sku                         0     191
name                        0     127
condition                   3       3
price                       0     132
highlight                 184       5
sellerName                187       3
aggregateRating.rating    189       4

After:
                                                    dtype  total  not_null  \
url                                                   str    191       191
sku                                                   str    191       191
data.extractedAt        datetime64[us, America/Sao_Paulo]    191       191
imageUrl                                              str    191       191
name                                                  str    191       191
condition                                             str    191       188
price                                               int64    191       191
highlight                                             str    191        12
sellerName                                            str    191         9
aggregateRating.rating                            float64    191         7

                        nulls  unique
url                         0     191
sku                         0     191
data.extractedAt            0       5
imageUrl                    0     187
name                        0     127
condition                   3       3
price                       0     132
highlight                 179       5
sellerName                182       3
aggregateRating.rating    184       4

In [14]:
def impute_values(df: pd.DataFrame) -> pd.DataFrame:
    if 'highlight' in df.columns:
        df.loc[df['highlight'].isna(), 'highlight'] = 'Sem destaque'

    return df

df = impute_values(df)
if 'highlight' in df.columns:
    resume = pd.DataFrame({
        'highlight': {
            'dtype': df['highlight'].dtype,
            'total': len(df['highlight']),
            'not_null': df['highlight'].notna().sum(),
            'nulls': df['highlight'].isna().sum(),
            'unique': df['highlight'].nunique()
        }
    })
    print(resume)

         highlight
dtype          str
total          191
not_null       191
nulls            0
unique           6

In [15]:
if 'price' in df.columns:
    resume = pd.DataFrame({
        'price': {
            'dtype': df['price'].dtype,
            'total': len(df['price']),
            'not_null': df['price'].notna().sum(),
            'nulls': df['price'].isna().sum()
        }
    })
    print(f"\nBefore:\n{resume}")

def treat_outliers(df: pd.DataFrame) -> pd.DataFrame:
    #price
    if 'price' in df.columns:
        df = df.dropna(subset='price', ignore_index=True)

    #aggregateRating.rating
    if 'aggregateRating.rating' in df.columns:
        df.loc[(df['aggregateRating.rating'] < 1) | (df['aggregateRating.rating'] > 5), 'aggregateRating.rating'] = np.nan

    return df

df = treat_outliers(df)
if 'price' in df.columns:
    resume = pd.DataFrame({
        'price': {
            'dtype': df['price'].dtype,
            'total': len(df['price']),
            'not_null': df['price'].notna().sum(),
            'nulls': df['price'].isna().sum()
        }
    })
    print(f"\nAfter:\n{resume}")

if 'aggregateRating.rating' in df.columns:
    print("\nOutliers: \n")
    for i in df['aggregateRating.rating']:
        if (i < 1) or (i > 5):
            print(i)

Before:
          price
dtype     int64
total       191
not_null    191
nulls         0

After:
          price
dtype     int64
total       191
not_null    191
nulls         0

Outliers:

In [16]:
columns_to_rename = {
    'url': 'url',
    'sku': 'sku',
    'data.extractedAt': 'extracted_at',
    'imageUrl': 'image_url',
    'categoryId': 'category_id',
    'domainId': 'domain_id',
    'name': 'name',
    'condition': 'condition',
    'currency': 'currency',
    'currencyRaw': 'currency_raw',
    'price': 'price',
    'highlight': 'highlight',
    'isBestSeller': 'is_best_seller',
    'isPowerSeller': 'is_power_seller',
    'powerSellerStatusTitle': 'power_seller_status_title',
    'ean': 'ean',
    'sellerId': 'seller_id',
    'sellerName': 'seller_name',
    'sellerCity': 'seller_city',
    'sellerState': 'seller_state',
    'sellerCountry': 'seller_country',
    'aggregateRating.rating': 'rating',
    'aggregateRating.reviewCount': 'review_count',
}

def rename_columns(df: pd.DataFrame, columns_to_rename: dict) -> pd.DataFrame:
    for key, value in columns_to_rename.items():
        df.rename(columns={key: value}, inplace=True)

    return df

df = rename_columns(df, columns_to_rename)
df.head(0)

Empty DataFrame
Columns: [url, sku, extracted_at, image_url, name, condition, price, highlight, seller_name, rating]
Index: []

In [17]:
valores_distintos = df['seller_name'].unique()
valores_distintos

<StringArray>
['Mobi Phone', nan, 'Trocafy', 'Trocafone']
Length: 4, dtype: str